print("Welcome to a Band Name generator")
name1 = input("what is the name of the city you grew up in ? ")
print(name1)
name2 = input("what is your nick name?")
print(name2)
print("Your band name could be " + name1 + " " + name2)