# print(type("Hello"))
# print(type(1))
# print(type(1.0))
# print(type(True))
# print(type([1, 2, 3]))
# print(type((1, 2, 3)))
# print(type({"name": "John", "age": 23}))
# print(type({1, 2, 3}))
# print(type(None))
# print(type(type))
# print(type(print))
# print(type(len))
# print(type(type(1)))
# int("123")
# print(int("123"))   
# print(int(123.45))
# print(int("123.45"))
print("Number of letters in your name: " + str(len(input("What is your name? "))))